export const profile = {
  name: "Shaik Abdul Hafeez",
  title: "Software Engineer — AI Agents & Full‑Stack",
  location: "Hyderabad, Telangana",
  summary:
    "Software Engineer specializing in AI agents, multimodal RAG, and full‑stack development. I design intelligent systems that retrieve, reason, and act—backed by scalable APIs, robust testing, and clean UX.",
  contact: {
    email: "shaik.abdulhafeez323@gmail.com",
    phone: "+91-6281675266",
    website: "", // e.g. "https://yourdomain.com"
    linkedin: "", // e.g. "https://linkedin.com/in/your-handle"
    github: "", // e.g. "https://github.com/your-handle"
  },
  experience: [
    {
      role: "Software Engineer",
      company: "ZerocodeHR",
      location: "Hyderabad, Telangana",
      start: "June 2024",
      end: "Present",
      bullets: [
        "Designed and implemented a multifunctional company chatbot integrated with Gmail, Google Chat, and Jira (via MCP) to automate ticketing and daily reporting.",
        "Added intelligent agent features for page-aware guidance, in‑page data analysis, and chart generation with actionable insights.",
        "Implemented guardrails to block toxicity, prevent prompt injection, and applied rate limiting for secure, reliable performance.",
        "Built advanced AI agents using LangChain and OpenAI Agent SDK for site building, report generation, data modeling, and site automation.",
        "Developed custom agents for SQL/NoSQL/document retrieval; built high‑accuracy RAG pipelines with LlamaIndex, ChromaDB, and DeepSeek.",
        "Fine‑tuned open‑source LLMs (e.g., DeepSeek) to improve domain‑specific response accuracy; integrated multimodal RAG for Excel/PPT/PDF.",
        "Developed scalable FastAPI backends and ML model APIs on AWS Lambda + API Gateway.",
        "Automated testing using Java Selenium + TestNG with Spring Boot, reducing test suite time by 1+ hour and adding 100+ stable test cases.",
        "Performed performance/load testing with K6, improving backend‑to‑frontend integration and reliability.",
      ],
    },
    {
      role: "Full Stack Web Developer - Intern",
      company: "Xyenta Solutions",
      location: "Hyderabad, Telangana",
      start: "Jan 2024",
      end: "June 2024",
      bullets: [
        "Developed Spring Boot APIs in Java with DTOs, repositories, and configurations.",
        "Built Flutter pages in Dart for a fintech prototype; optimized logic for iOS/Android responsiveness.",
        "Ensured seamless backend‑to‑frontend integration and performance; collaborated via Git/GitHub.",
      ],
    },
    {
      role: "Web Developer - Intern",
      company: "Codecrux Web Technologies",
      location: "Hyderabad, Telangana",
      start: "June 2022",
      end: "Aug 2022",
      bullets: [
        "Developed responsive websites with HTML, CSS, JavaScript; used Webflow, WordPress, Bootstrap, Tailwind.",
        "Learned CI/CD workflows to improve deployment efficiency and reliability.",
      ],
    },
  ],
  projects: [
    {
      name: "SNEKO Food Delivery Website",
      type: "Full Stack",
      bullets: [
        "Responsive food delivery site using React for interactive UI.",
        "Express + Node.js server with Firebase auth (Gmail + phone OTP) and database.",
        "Version control in Git and wireframing in Figma.",
      ],
      tech: ["React", "Node.js", "Express", "Firebase", "Figma", "Git"],
    },
    {
      name: "Rent Management Website",
      type: "Full Stack",
      bullets: [
        "Flask‑based app for monthly rents and transaction logging.",
        "Stored rental data to Excel for simple operations and export.",
      ],
      tech: ["Flask", "Python", "Excel"],
    },
  ],
  education: [
    {
      school: "The ICFAI University For Higher Education",
      credential: "B.Tech in Computer Science Engineering",
      start: "Sept 2020",
      end: "Aug 2024",
      gpa: "9.55/10.0",
    },
    {
      school: "Sri Chaitanya Junior College",
      credential: "Math, Physics and Chemistry",
      start: "June 2018",
      end: "May 2020",
      gpa: "9.88/10.0",
    },
    {
      school: "Bhashyam Public School",
      credential: "Schooling",
      end: "May 2018",
      gpa: "10/10.0",
    },
  ],
  publications: [
    {
      title: "Neural Network Analysis for Early Detection and Prediction of Mental Depression",
      venue: "ISDIA Dubai Conference (Springer)",
      year: "2024",
      doi: "10.1007/978-981-97-4895-2_21",
    },
  ],
  skills: {
    languages: ["C", "Java", "Python", "JavaScript", "Dart", "HTML", "CSS"],
    frameworks: [
      "React.js",
      "Next.js",
      "Node.js",
      "Flutter",
      "Spring Boot",
      "Flask",
      "Selenium",
      "K6",
      "TestNG",
      "Phidata",
      "LangChain",
      "Crew.ai",
    ],
    tools: [
      "WordPress",
      "Bootstrap",
      "Tailwind CSS",
      "Webflow",
      "MongoDB",
      "Firebase",
      "Figma",
      "Git",
      "GitHub",
      "PostgreSQL",
      "MySQL",
    ],
    technical: [
      "Full‑Stack Web Development",
      "Machine Learning",
      "NLP",
      "Neural Networks",
      "Data Visualization",
      "Data Scraping",
      "Testing & Automation",
      "Data Structures",
      "OOP",
    ],
    editing: ["UI/UX Design", "Photoshop", "Video Editing", "Adobe XD", "Canva"],
    soft: [
      "Communication",
      "Leadership",
      "Collaboration",
      "Inquisitive",
      "Problem Solving",
      "Self‑Motivation",
      "Quick Learner",
    ],
  },
}
