export const profile = {
  name: "Shaik Abdul Hafeez",
  title: "Software Engineer — AI & Full‑Stack",
  location: "Hyderabad, Telangana",
  summary:
    "Software Engineer specializing in AI agents, multimodal RAG, and full‑stack development. I design intelligent systems that retrieve, reason, and act—backed by scalable APIs, robust testing, and clean UX.",
  contact: {
    email: "shaik.abdulhafeez323@gmail.com",
    phone: "+91-6281675266",
    website: "https://portfolio.shaikabdulhafeez.link/", // e.g. "https://yourdomain.com"
    linkedin: "https://www.linkedin.com/in/shaik-abdul-hafeez-95a917220/", // e.g. "https://linkedin.com/in/your-handle"
    github: "https://github.com/ShaikAbdulHafeez03", // e.g. "https://github.com/your-handle"
  },
  experience: [
    {
      role: "Software Engineer",
      company: "ZerocodeHR",
      location: "Hyderabad, Telangana",
      start: "June 2024",
      end: "Present",
      bullets: [
    "Designed and implemented a multifunctional company chatbot to assist clients, developers, and professional services teams with company processes, configuration, and code-related queries. Integrated with Gmail and Google Chat, and extended Jira via MCP to automate ticket creation, updates, and daily reporting. Enhanced functionality by adding intelligent agent features: agents explain the current page context, guide user navigation, perform in-page data analysis, and generate charts from grid/tabular data with actionable insights. Implemented guardrails to block toxicity, prevent prompt injection, and added rate limiting to ensure secure, reliable, and scalable performance.",
    "Designed and implemented advanced AI agents using LangChain and OpenAI Agent SDK; created agents for site building, report generation, data modeling, and site automation.",
    "Data Analysis Agent Built a secure, Docker-isolated analytics system that automatically processes user uploaded csv, excel files using Pandas and Plotly, then generates professional LaTeX PDF reports. Enabled safe, automated, and scalable data analysis without manual coding or security risks..",
    "Built and optimized high-accuracy Retrieval-Augmented Generation (RAG) pipelines, working extensively with open-source frameworks/models such as Langchain, LlamaIndex, QdrantDB and GPT-oss. Designed custom ingestion, chunking, and retrieval strategies for handling large-scale document processing.",
    "Fine-tuned open-source LLMs like DeepSeek, Qwen to improve contextual understanding and response accuracy in domain-specific applications.",
    "Architected and developed scalable and high-performance backend APIs using FastAPI, optimizing response times and enabling seamless integration with AI-driven applications. integrated prometheus, gafana loki, MLFlow for metrics logging and model tracing.",
    "Developed custom AI agents capable of retrieving, processing, and reasoning over SQL databases, NoSQL stores, and document-based data, improving data accessibility and operational efficiency.",
    "Developed and deployed scalable ML model APIs using AWS Lambda, API Gateway, and IAM, ensuring seamless integration with enterprise applications.",
    "QAAutomation, automated testing frameworks using Java, Selenium, TestNG, and Spring Boot, improving test coverage and overall reliability. Streamlined and refactored three major test suites—reducing total execution time by over 50 percent (from 2 hours to 1 hour) and fixing more than 200 test cases to enhance stability"
  ],
    },
    {
      role: "Full Stack Web Developer - Intern",
      company: "Xyenta Solutions",
      location: "Hyderabad, Telangana",
      start: "Jan 2024",
      end: "June 2024",
      bullets: [
        "Developed Spring Boot APIs in Java with DTOs, repositories, and configurations.",
        "Built Flutter pages in Dart for a fintech prototype; optimized logic for iOS/Android responsiveness.",
        "Ensured seamless backend‑to‑frontend integration and performance; collaborated via Git/GitHub.",
      ],
    },
    {
      role: "Web Developer - Intern",
      company: "Codecrux Web Technologies",
      location: "Hyderabad, Telangana",
      start: "June 2022",
      end: "Aug 2022",
      bullets: [
        "Developed responsive websites with HTML, CSS, JavaScript; used Webflow, WordPress, Bootstrap, Tailwind.",
        "Learned CI/CD workflows to improve deployment efficiency and reliability.",
      ],
    },
  ],
projects: [
  {
    name: "SNEKO Food Delivery Website",
    type: "Full Stack",
    bullets: [
      "Developed a dynamic and responsive food delivery platform with an admin dashboard for order management. https://sneko-git-main-snekos-projects.vercel.app/",
      "React frontend with Firebase authentication (Gmail and phone OTP) and Firebase database integration.",
      "Node.js + Express backend ensuring secure, scalable communication between frontend and server.",
      "Collaborated in a startup environment, focusing on performance and seamless user experience.",
    ],
    tech: ["React", "Node.js", "Express", "Firebase", "Figma", "Git", "Jwt"],
  },
  {
    name: "TrendCaster",
    type: "AI + Automation",
    bullets: [
      "Built an AI-driven system to identify trending topics in specific niches and news domains.",
      "Automated adaptation of news into social media posts, YouTube videos, and Reels.",
      "Integrated image generation models for creating news visuals and automated multi-platform posting.",
      "Generated templates dynamically, combining visuals, headings, and text into social-ready content.",
    ],
    tech: ["Python", "LangChain", "OpenAI Agent sdk", "gemini API", "FFMPEG", "FreeSound API", "Fastapi", "Instagram API", "Twitter API"],
  },
  {
    name: "Rapport Agent",
    type: "AI Agent System",
    bullets: [
      "Developed a multi-agent data analysis system for CSV/Excel uploads.",
      "Implemented specialized agents (Pay Equity, Attrition, HR) to generate insights and reports.",
      "Built automated charting, data exploration, and interactive conversation features for business analysis.",
      "Enabled AI-driven HR analytics via safe sandboxed execution environments.",
    ],
    tech: ["Python", "Pandas", "Plotly", "OpenAI Agent SDK", "LangChain", "Docker"],
  },
  {
    name: "Portfolio Website",
    type: "Full Stack (Next.js)",
    bullets: [
      "Designed and developed a modern personal portfolio using Next.js and Tailwind CSS.",
      "Integrated dynamic sections for projects, experiences, and contact forms powered by Firebase backend.",
      "Implemented responsive animations and smooth routing using Framer Motion for an interactive experience.",
      "Optimized for SEO, Lighthouse performance, and fast loading across devices.",
    ],
    tech: ["Next.js", "Tailwind CSS", "Vercel"],
  },
   {
    name: "Rent Management Website",
    type: "Full Stack",
    bullets: [
      "Flask-based application for managing monthly rents and financial records.",
      "Automated transaction logging and export of data to Excel for offline access.",
      "Designed minimalistic UI for simplicity and data accessibility.",
    ],
    tech: ["Flask", "Python", "Excel"],
  },
  ],
  education: [
    {
      school: "The ICFAI University For Higher Education",
      credential: "B.Tech in Computer Science Engineering",
      start: "Sept 2020",
      end: "Aug 2024",
      gpa: "9.55/10.0",
    },
    {
      school: "Sri Chaitanya Junior College",
      credential: "Math, Physics and Chemistry",
      start: "June 2018",
      end: "May 2020",
      gpa: "9.88/10.0",
    },
    {
      school: "Bhashyam Public School",
      credential: "Schooling",
      end: "May 2018",
      gpa: "10/10.0",
    },
  ],
  publications: [
    {
      title: "Neural Network Analysis for Early Detection and Prediction of Mental Depression",
      venue: "ISDIA Dubai Conference (Springer)",
      year: "2024",
      doi: "10.1007/978-981-97-4895-2_21",
    },
  ],
  skills: {
    languages: ["C", "Java", "Python", "JavaScript", "Dart", "HTML", "CSS"],
    frameworks: [
      "React.js",
      "Next.js",
      "Node.js",
      "Flutter",
      "Spring Boot",
      "Flask",
      "Selenium",
      "K6",
      "TestNG",
      "Phidata",
      "LangChain",
      "Crew.ai",
      "open ai agent sdk",
      "fast api",
      "pandas",
      "numpy",
      "plotly"
    ],
    tools: [
      "WordPress",
      "Bootstrap",
      "Tailwind CSS",
      "Webflow",
      "MongoDB",
      "Firebase",
      "Figma",
      "Git",
      "GitHub",
      "PostgreSQL",
      "MySQL",
    ],
    technical: [
      "Full‑Stack Web Development",
      "Machine Learning",
      "NLP",
      "Neural Networks",
      "Data Visualization",
      "Data Scraping",
      "Testing & Automation",
      "Data Structures",
      "OOP",
    ],
    editing: ["UI/UX Design", "Photoshop", "Video Editing", "Adobe XD", "Canva"],
    soft: [
      "Communication",
      "Leadership",
      "Collaboration",
      "Inquisitive",
      "Problem Solving",
      "Self‑Motivation",
      "Quick Learner",
    ],
  },
}
